"""Replay frozen Mink inputs through an independent numerical reference.

No hardware, camera, JAX runtime, or application checkout is required. Extract
reference-source.tar.gz first, then run from the Axol repository root:

    PYTHONPATH=. python tests/tools/mink_ik_reference.py \
      --reference-root /tmp/mink-source/mink_reference \
      --replay-fixture --write-fixture /tmp/mink-native

Without --write-fixture, compare the two real solvers and print a report only.
The reference files are verified before import under an isolated namespace.
Reference expectations are never generated by the production implementation.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import importlib.metadata
import json
import platform
import sys
import types
from dataclasses import asdict
from pathlib import Path

import numpy as np

REFERENCE_COMMIT = "b32002c0507db5ab03a421c9fb1f2ebf4b7fd49b"
COMMITTED_FIXTURES = Path(__file__).resolve().parents[1] / "data" / "mink_ik_reference"
INPUT_NAMES = (
    "rest14",
    "left_pos",
    "left_rot",
    "right_pos",
    "right_rot",
    "reset_before",
    "fk_joints",
    "pose6",
    "current_wire_pose6",
)


def load_reference(source: Path):
    # Check every imported numerical source and asset before executing any of
    # the reference tree. A current-port checkout is not an independent oracle.
    expected = json.loads((COMMITTED_FIXTURES / "provenance.json").read_text())
    archive = COMMITTED_FIXTURES / "reference-source.tar.gz"
    if (
        hashlib.sha256(archive.read_bytes()).hexdigest()
        != expected["reference_archive_sha256"]
    ):
        raise ValueError("Reference source archive hash differs from provenance")
    if expected["reference_commit"] != REFERENCE_COMMIT:
        raise ValueError("Reference fixture commit does not match the pinned baseline")
    if source_hashes(source) != expected["source_sha256"]:
        raise ValueError("Reference source/assets differ from the pinned baseline")
    validate_shared_name_tables()
    namespace = "_mink_independent_reference"
    for name in list(sys.modules):
        if name == namespace or name.startswith(namespace + "."):
            del sys.modules[name]
    package = types.ModuleType(namespace)
    package.__path__ = [str(source)]
    sys.modules[namespace] = package
    return (
        importlib.import_module(f"{namespace}.ik"),
        importlib.import_module(f"{namespace}.fk"),
    )


def validate_shared_name_tables():
    """The reference solver's only SDK imports are these unchanged name tables."""
    from almond_axol.constants import Joint, urdf_arm_joint_names, urdf_body_name

    for side, is_left in (("left", True), ("right", False)):
        expected = [
            f"{side}_{suffix}"
            for suffix in ("s1_0", "s2_0", "s3_0", "e1_0", "e2_0", "w1_0", "w2_0")
        ]
        if urdf_arm_joint_names(is_left=is_left) != expected:
            raise ValueError(
                "Shared SDK joint name table differs from pinned reference"
            )
        for joint, suffix in (
            (Joint.GRIPPER, "gripper"),
            (Joint.ELBOW, "e2"),
            (Joint.SHOULDER_1, "s2"),
        ):
            if urdf_body_name(joint, is_left=is_left) != f"{side}_{suffix}":
                raise ValueError(
                    "Shared SDK body name table differs from pinned reference"
                )


def runtime_versions() -> dict[str, str]:
    versions = {
        name: importlib.metadata.version(name)
        for name in ("mujoco", "mink", "daqp", "qpsolvers", "numpy")
    }
    expected = json.loads((COMMITTED_FIXTURES / "provenance.json").read_text())
    if versions != expected["runtime_versions"]:
        raise RuntimeError(
            "Reference numerical parity requires the pinned numerical runtime: "
            f"expected {expected['runtime_versions']}, found {versions}"
        )
    return versions


def runtime_platform() -> dict[str, str]:
    return {"system": platform.system(), "machine": platform.machine()}


def load_fixture(path: Path, *, require_native: bool = False):
    """Validate stored expectations before tests use them as an oracle.

    Native overrides must use the exact frozen inputs, sources, configuration,
    dependency versions, and current architecture. Tests never fetch a baseline
    or regenerate expectations implicitly.
    """
    provenance = json.loads((path / "provenance.json").read_text())
    if provenance["reference_commit"] != REFERENCE_COMMIT:
        raise ValueError("Fixture reference commit differs from the pinned baseline")
    fixture = path / "stream.npz"
    if hashlib.sha256(fixture.read_bytes()).hexdigest() != provenance["fixture_sha256"]:
        raise ValueError("Fixture archive hash does not match provenance")
    with np.load(fixture, allow_pickle=False) as saved:
        arrays = {name: saved[name].copy() for name in saved.files}
    if require_native:
        frozen, original = load_fixture(COMMITTED_FIXTURES)
        for name in (
            "source_sha256",
            "production_source_sha256",
            "reference_archive_sha256",
            "config",
            "stream",
            "runtime_versions",
        ):
            if provenance[name] != original[name]:
                raise ValueError(
                    f"Native fixture {name} differs from the pinned baseline"
                )
        if provenance.get("input_fixture_sha256") != original["fixture_sha256"]:
            raise ValueError(
                "Native fixture was not replayed from the committed inputs"
            )
        if provenance.get("runtime_platform") != runtime_platform():
            raise ValueError("Native fixture was generated on a different platform")
        if provenance["runtime_versions"] != runtime_versions():
            raise ValueError(
                "Native fixture numerical runtime differs from this process"
            )
        for name in INPUT_NAMES:
            if arrays[name].dtype != frozen[name].dtype or not np.array_equal(
                arrays[name], frozen[name]
            ):
                raise ValueError(f"Native fixture changed frozen input {name}")
    return arrays, provenance


def source_hashes(source: Path) -> dict[str, str]:
    paths = [
        source / name
        for name in (
            "ik.py",
            "ik_config.py",
            "ik_mink_backend.py",
            "ik_mujoco_model.py",
            "vendor_io.py",
            "fk.py",
        )
    ]
    paths.extend(path for path in (source / "assets").rglob("*") if path.is_file())
    return {
        str(path.relative_to(source)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(paths)
    }


def replay_reference(source: Path):
    """Compute native reference expectations using the committed stream inputs.

    Cross-architecture floating point equality is not promised by MuJoCo/DAQP
    or NumPy. Equality between the independent reference and production solvers on the same
    platform remains exact, including recurrent previous-solution seeds.
    """
    versions = runtime_versions()
    arrays, original = load_fixture(COMMITTED_FIXTURES)
    reference, reference_fk = load_reference(source)
    arrays = {name: arrays[name] for name in INPUT_NAMES}
    solver = reference.MinkIK()
    if asdict(solver.config) != original["config"]:
        raise ValueError("Reference config differs from the committed baseline")
    rest = arrays["rest14"]
    solver.set_rest_posture(rest)
    solver.reset_tracking_state()
    q = rest.copy()
    joints, failures = [], []
    for tick in range(len(arrays["reset_before"])):
        if arrays["reset_before"][tick]:
            q = rest.copy()
            solver.reset_tracking_state()
        q = solver.solve(
            q,
            (arrays["left_pos"][tick], arrays["left_rot"][tick]),
            (arrays["right_pos"][tick], arrays["right_rot"][tick]),
        )
        joints.append(q.copy())
        failures.append(solver.fail_count)
    arrays["expected_joints"] = np.stack(joints)
    arrays["expected_fail_count"] = np.asarray(failures, dtype=np.int64)
    poses = [reference.pose6_to_pos_rot_np(pose) for pose in arrays["pose6"]]
    arrays["pose_positions"] = np.stack([p for p, _ in poses])
    arrays["pose_rotations"] = np.stack([r for _, r in poses])
    fk = [
        [
            reference_fk.gripper_pose_from_joints(
                joints[side * 7 : (side + 1) * 7], name
            )
            for side, name in enumerate(("left", "right"))
        ]
        for joints in arrays["fk_joints"]
    ]
    arrays["fk_positions"] = np.asarray([[p for _, p in sample] for sample in fk])
    arrays["fk_rotations"] = np.asarray([[r for r, _ in sample] for sample in fk])
    replay_world_frame(reference, arrays)
    provenance = {
        key: original[key]
        for key in (
            "reference_commit",
            "reference_module",
            "source_sha256",
            "production_source_sha256",
            "reference_archive_sha256",
            "reference_normalization",
            "current_wire_reference",
            "config",
            "stream",
            "fk_reference",
            "fk_sample_count",
            "fk_seed",
            "pose_conversion_count",
            "hardware_access",
        )
    }
    provenance.update(
        runtime_versions=versions,
        runtime_platform=runtime_platform(),
        input_fixture_sha256=original["fixture_sha256"],
    )
    return arrays, provenance


def replay_world_frame(reference, arrays):
    """Replay frozen public-world poses using independent decoding and geometry."""
    solver = reference.MinkIK()
    rest = arrays["rest14"]
    solver.set_rest_posture(rest)
    solver.reset_tracking_state()
    q = rest.copy()
    n = len(arrays["reset_before"])
    positions = np.empty((n, 2, 3), dtype=np.float32)
    rotations = np.empty((n, 2, 3, 3), dtype=np.float32)
    expected = np.empty((n, 14), dtype=np.float32)
    inverse_yaw = np.array([[0.0, 1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0]])
    origin = np.array([-2.77556e-17, -6.93889e-18, 0.86])
    for tick in range(n):
        if arrays["reset_before"][tick]:
            q = rest.copy()
            solver.reset_tracking_state()
        targets = []
        for side in range(2):
            position, rotation = reference.pose6_to_pos_rot_np(
                arrays["current_wire_pose6"][tick, side]
            )
            positions[tick, side] = origin + inverse_yaw @ (position - origin)
            rotations[tick, side] = inverse_yaw @ rotation
            targets.append((positions[tick, side], rotations[tick, side]))
        q = solver.solve(q, *targets)
        expected[tick] = q
    arrays.update(
        current_wire_positions=positions,
        current_wire_rotations=rotations,
        current_wire_joints=expected,
    )


def compare_port(arrays):
    from almond_axol.policy.mink_ik import (
        MinkIK,
        pose6_to_pos_rot_np,
        pose6_world_to_model,
    )

    solver = MinkIK()
    rest = arrays["rest14"]
    solver.set_rest_posture(rest)
    solver.reset_tracking_state()
    q = rest.copy()
    worst = 0.0
    for tick in range(len(arrays["expected_joints"])):
        if arrays["reset_before"][tick]:
            q = rest.copy()
            solver.reset_tracking_state()
        q = solver.solve(
            q,
            (arrays["left_pos"][tick], arrays["left_rot"][tick]),
            (arrays["right_pos"][tick], arrays["right_rot"][tick]),
        )
        np.testing.assert_array_equal(
            q, arrays["expected_joints"][tick], err_msg=f"tick {tick}"
        )
        assert solver.fail_count == arrays["expected_fail_count"][tick]
        worst = max(worst, float(np.max(np.abs(q - arrays["expected_joints"][tick]))))
    worst_pos, worst_rot = 0.0, 0.0
    for sample, joints in enumerate(arrays["fk_joints"]):
        for side, (pos, rotation) in enumerate(solver.fk(joints)):
            worst_pos = max(
                worst_pos,
                float(np.max(np.abs(pos - arrays["fk_positions"][sample, side]))),
            )
            worst_rot = max(
                worst_rot,
                float(np.max(np.abs(rotation - arrays["fk_rotations"][sample, side]))),
            )
    assert worst_pos <= 1e-5 and worst_rot <= 1e-4
    for sample, pose in enumerate(arrays["pose6"]):
        position, rotation = pose6_to_pos_rot_np(pose)
        np.testing.assert_array_equal(position, arrays["pose_positions"][sample])
        np.testing.assert_array_equal(rotation, arrays["pose_rotations"][sample])
    solver.reset_tracking_state()
    q = rest.copy()
    for tick, poses in enumerate(arrays["current_wire_pose6"]):
        if arrays["reset_before"][tick]:
            q = rest.copy()
            solver.reset_tracking_state()
        targets = [pose6_world_to_model(pose) for pose in poses]
        for side, (position, rotation) in enumerate(targets):
            np.testing.assert_array_equal(
                position, arrays["current_wire_positions"][tick, side]
            )
            np.testing.assert_array_equal(
                rotation, arrays["current_wire_rotations"][tick, side]
            )
        q = solver.solve(q, *targets)
        np.testing.assert_array_equal(
            q, arrays["current_wire_joints"][tick], err_msg=f"world-frame tick {tick}"
        )
    return {
        "world_frame_solver_steps": len(arrays["current_wire_pose6"]),
        "world_frame_conversion_exact": True,
        "solver_steps": len(arrays["expected_joints"]),
        "max_joint_difference_rad": worst,
        "fk_position_max_difference_m": worst_pos,
        "fk_rotation_max_difference": worst_rot,
        "pose_conversion_exact": True,
        "fail_count": solver.fail_count,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-root", required=True, type=Path)
    parser.add_argument("--write-fixture", type=Path)
    parser.add_argument(
        "--replay-fixture",
        action="store_true",
        required=True,
        help="Replay exact committed inputs to create architecture-native expectations",
    )
    args = parser.parse_args()
    arrays, provenance = replay_reference(args.reference_root.resolve())
    report = compare_port(arrays)
    provenance["port_comparison"] = report
    if args.write_fixture is not None:
        args.write_fixture.mkdir(parents=True, exist_ok=True)
        fixture = args.write_fixture / "stream.npz"
        np.savez_compressed(fixture, **arrays)
        provenance["fixture_sha256"] = hashlib.sha256(fixture.read_bytes()).hexdigest()
        (args.write_fixture / "provenance.json").write_text(
            json.dumps(provenance, indent=2) + "\n"
        )
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
